name: github pages

on:
  push:
    branches:
      - master # Set a branch to deploy
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4

      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup xq
        run: curl -sSL https://bit.ly/install-xq | sudo bash

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build static site
        run: hugo --minify

      - name: Unminify index.xml
        run: mv public/index.xml public/minified.xml && xq public/minified.xml > public/index.xml

      - name: Build Elm widget
        run: npm ci && node_modules/.bin/elm make src/Main.elm --optimize --output public/widget.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
